
port = 50051
node_id = 1
persistence_dir = "out/"
max_message_size_bytes = 4096
max_batch_size = 512
min_batch_interval_ms = 2
metrics_port = 51051
[[cluster_nodes]]
endpoint = "http://[::1]:50051"
node_id = 1
[[cluster_nodes]]
endpoint = "http://[::1]:50052"
node_id = 2
[[cluster_nodes]]
endpoint = "http://[::1]:50053"
node_id = 3
