
port = 50051
node_id = 1
persistence_dir = "out/"
max_message_size_bytes = 4096
max_batch_size = 512
min_batch_interval_ms = 2
metrics_port = 51051
enable_otel_tracing = false
use_capnp_transport = false
capnp_port = 51151
[[cluster_nodes]]
endpoint = "http://[::1]:50051"
capnp_endpoint = "[::1]:51151"
node_id = 1
[[cluster_nodes]]
endpoint = "http://[::1]:50052"
capnp_endpoint = "[::1]:51152"
node_id = 2
[[cluster_nodes]]
endpoint = "http://[::1]:50053"
capnp_endpoint = "[::1]:51153"
node_id = 3
