
port = 50052
node_id = 2
persistence_dir = "out2/"
max_message_size_bytes = 4096
[[cluster_nodes]]
endpoint = "http://[::1]:50051"
node_id = 1
[[cluster_nodes]]
endpoint = "http://[::1]:50052"
node_id = 2
[[cluster_nodes]]
endpoint = "http://[::1]:50053"
node_id = 3
