syntax = "proto3";
package raftproto;

message AppendEntriesRequest {
    uint64 term = 1;
    uint32 leader_id = 2;
    uint64 prev_log_index = 3;
    uint64 prev_log_term = 4;
    repeated LogEntry entries = 5; // TODO delete this
    uint64 request_id = 6;
    LogEntry entry = 7;
}

message AppendEntriesAcknowledge {
    uint64 term = 1;
    uint64 log_index = 2;
    uint64 request_id = 3;
    bool ok = 4;
}

message AppendEntriesResponse {
    bool ok = 1;
}

message LogEntry {
    uint64 index = 1;
    bytes data = 2;
    uint64 batch_index = 3;
    uint64 term = 4;
}

message VoteRequest {
    uint64 term = 1;
    uint32 candidate_id = 2;
    uint64 last_log_index = 3;
    uint64 last_log_term = 4;
    uint64 request_id = 5;
}

message VoteResponse {
    bool vote_granted = 1;
    uint64 request_id = 2;
    uint64 term = 3;
}

message PutRequest {
    string id = 1;
    string payload = 2;
    uint32 node_id = 3;
}

message PutBatchRequest {
    repeated PutRequest put_request = 1;
}

enum ResponseType {
    RESPONSE_TYPE_UNSPECIFIED = 0;
    RESPONSE_TYPE_OK = 1;
    RESPONSE_TYPE_INVALID = 2;
}

message PutResponse {
    string id = 1;
    ResponseType response_type = 2;
    string message = 3;
    uint32 node_id = 4;
    string batch_id = 5;
}

message PutBatchResponse {
    repeated PutResponse responses = 1;
}

message ConnectRequest {
    uint32 node_id = 1;
}

message ConnectResponse {
    bool ok = 1;
}

message QuorumMessage {
    oneof message_payload {
        ConnectRequest connect_request_option = 1;
        ConnectResponse connect_response_option = 2;
        VoteRequest vote_request_option = 3;
        VoteResponse vote_response_option = 4;
        AppendEntriesRequest append_entries_request_option = 5;
        AppendEntriesAcknowledge append_entries_acknowledge_option = 6;
    }
}

message StreamResponse {

}

service Raft {
    rpc AppendEntries (AppendEntriesRequest) returns (AppendEntriesResponse);
    rpc RequestVote (VoteRequest) returns (VoteResponse);
    rpc PutBatch (PutBatchRequest) returns (PutBatchResponse);
    rpc Messages(stream QuorumMessage) returns (StreamResponse);
}

