syntax = "proto3";
package raftproto;

message RemoteAppendEntriesRequest {
    uint64 term = 1;
    uint32 leader_id = 2;
    uint64 prev_log_index = 3;
    uint64 prev_log_term = 4;
    repeated RemoteLogEntry entries = 5; // TODO delete this
    uint64 request_id = 6;
    RemoteLogEntry entry = 7;
    uint64 commit_index = 8;
}

message RemoteAppendEntriesAcknowledge {
    uint64 last_log_term = 1;
    uint64 last_log_index = 2;
    uint64 request_id = 3;
    bool ok = 4;
}

message RemoteAppendEntriesResponse {
    bool ok = 1;
}

message RemoteLogEntry {
    uint64 index = 1;
    bytes data = 2;
    uint64 batch_index = 3;
    uint64 term = 4;
    uint64 prev_log_term = 5;
    uint64 prev_log_index = 6;
    uint64 message_id = 7;
}

message RemoteVoteRequest {
    uint64 term = 1;
    uint32 candidate_id = 2;
    uint64 last_log_index = 3;
    uint64 last_log_term = 4;
    uint64 request_id = 5;
}

message RemoteVoteResponse {
    bool vote_granted = 1;
    uint64 request_id = 2;
    uint64 term = 3;
}

message RemotePutRequest {
    string id = 1;
    string payload = 2;
    uint32 node_id = 3;
}

message RemotePutBatchRequest {
    repeated RemotePutRequest put_request = 1;
    string batch_id = 2;
}

enum RemoteResponseType {
    REMOTE_RESPONSE_TYPE_UNSPECIFIED = 0;
    REMOTE_RESPONSE_TYPE_OK = 1;
    REMOTE_RESPONSE_TYPE_INVALID = 2;
}

message RemotePutResponse {
    string id = 1;
    RemoteResponseType response_type = 2;
    string message = 3;
    uint32 node_id = 4;
    string batch_id = 5;
}

message RemotePutBatchResponse {
    repeated RemotePutResponse responses = 1;
    string batch_id = 2;
}

message RemoteConnectRequest {
    uint32 node_id = 1;
}

message RemoteConnectResponse {
    bool ok = 1;
}

message TracingContext {
    repeated TracingContextEntry entries = 1;
}

message TracingContextEntry {
    string key = 1;
    string value = 2;
}

message RemoteTruncateLogRequest {
    uint64 prev_term = 1;
    uint64 prev_index = 2;
    uint64 term = 3;
    uint32 leader_id = 4;
    uint64 request_id = 5;
}

message RemoteTruncateLogResponse {
    uint64 request_id = 1;
    bool ok = 2;
}

message RemoteQuorumMessage {
    oneof message_payload {
        RemoteConnectRequest connect_request_option = 1;
        RemoteConnectResponse connect_response_option = 2;
        RemoteVoteRequest vote_request_option = 3;
        RemoteVoteResponse vote_response_option = 4;
        RemoteAppendEntriesRequest append_entries_request_option = 5;
        RemoteAppendEntriesAcknowledge append_entries_acknowledge_option = 6;
        RemotePutBatchRequest put_batch_request_option = 7;
        RemotePutBatchResponse put_batch_response_option = 8;
        RemoteTruncateLogRequest truncate_log_request_option = 9;
        RemoteTruncateLogResponse truncate_log_response_option = 10;
    }

    TracingContext tracing_context = 16;
}

message StreamResponse {

}

service Raft {
    rpc AppendEntries (RemoteAppendEntriesRequest) returns (RemoteAppendEntriesResponse);
    rpc RequestVote (RemoteVoteRequest) returns (RemoteVoteResponse);
    rpc PutBatch (RemotePutBatchRequest) returns (RemotePutBatchResponse);
    rpc Messages(stream RemoteQuorumMessage) returns (StreamResponse);
}

